### ISSUE TITLE
Atomikos JMS creates transactions for an empty queue

### ISSUE THREAD

**Issue by pmbsa** [atomikos/transactions-essentials#13]
Hi, I am trying to establish whether this is normal behavior or not. I have a springboot app running a camel route against an IBM MQ based JMS server. Everything seems to be working as you would expect having configured Atomikos to manage the 2PC for XA aside from the fact that the logs indicate that Atomikos Connection factory bean is repeatedly creating connections and transactions on a queue that is empty. It all works fine when a  message is delivered and the transaction is indeed managed. I am concerned about the transactions being created on the empty queue... its noticeable on the application restart as well that there are loads of heuristic transactions that then need committing which I find a little odd so I thought best to confirm I haven't gotten something very wrong.

thanks
Paul

**Comment by GuyPardon** [comment]
Paul,

Transactions for an empty queue are normal since we cannot determine beforehand if the queue is empty or not. Commit or rollback on empty queues has very minimal overhead - if any.

Re heuristics, not sure what you mean; it all depends on how you do system shutdown. We offer a free trial with free support to make sure your config is ok, in case you are interested.

Guy

**Comment by pmbsa** [comment]
Hi Guy, that would be great, if you let me know how to go about setting that up I can give some information on what we are doing and where Atomikos fits on. 
thanks
Paul

**Comment by GuyPardon** [comment]
Just apply here: https://www.atomikos.com/Main/ExtremeTransactionsFreeTrial

Thanks
